name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name:  Update contents
      run: |
        python contents.py
    - name: commit
      run: |
        git config --global user.email huakang.li@outlook.com
        git config --global user.name kayasu
        git add .
        git commit -m "update contents by script" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}